### ISSUE TITLE
A related paper on MLLM  and agents

### ISSUE THREAD

**Issue by chenllliang** [Yangyi-Chen/Multimodal-AND-Large-Language-Models#2]
Hi, we recently finished a paper "[Towards End-to-End Embodied Decision Making via Multi-modal Large Language Model: Explorations with GPT4-Vision and Beyond](https://arxiv.org/abs/2310.02071)"  ,we think it is highly related to this repo 😊. We would be glad if you could add it 😊😊, and we are always open to discuss.

**Comment by Yangyi-Chen** [comment]
Hi Liang,

Thanks for letting me know! Nice paper! I've added it to the Agent section.
