### ISSUE TITLE
Add some New Features

### ISSUE THREAD

**Issue by keesh0410** [Yangyi-Chen/Multimodal-AND-Large-Language-Models#5]
I'm thinking about enhancing this reading list. What if we include hyperlinks to the papers? 
This addition could significantly improve the usability of the list.

Alternatively, we could consider uploading the PDFs of the papers to this repository. 
That way, users can directly download the repository and begin their reading journey immediately.
 
Another option is to store the papers in Google Drive for easy access. 
This is awesome paper reading list!  Really helps a lot!

**Comment by Yangyi-Chen** [comment]
Thanks for your kind words and suggestions! Do you have any automated solution for including the hyperlinks or PDFs? 🤔
