### ISSUE TITLE
A related survey on MLLMs

### ISSUE THREAD

**Issue by zhenqincn** [Yangyi-Chen/Multimodal-AND-Large-Language-Models#6]
Dear Yangyi,

We have recently released a survey on MLLMs, titled "[The Synergy between Data and Multi-Modal Large Language Models: A Survey from Co-Development Perspective](https://arxiv.org/abs/2407.08583)". We believe this survey is highly relevant to your repo and would like to kindly request, if possible, to have it added to this repo. We look forward to discussing and potentially 
collaborating with you.

Best, 
Zhen Qin

**Comment by Yangyi-Chen** [comment]
Hi Zhen,
Thanks for sharing. I've read this paper and the literature review from the persepctive of synergy between data & model is interesting. I've added this paper to my collection, thanks!
